# Generated by Django 4.0.4 on 2022-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_history_photo_alter_news_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaching',
            name='date',
            field=models.DateField(null=True, verbose_name='Виберіть дату'),
        ),
    ]
