# Generated by Django 4.0.4 on 2022-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_preaching_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='day',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(null=True, verbose_name='дату публікування'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='day',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='history',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=500, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='preaching',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='preaching',
            name='date',
            field=models.DateField(null=True, verbose_name='дату публікування'),
        ),
        migrations.AlterField(
            model_name='preaching',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='preaching',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images_p/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='preaching',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
