# Generated by Django 4.0.4 on 2022-04-24 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_contacts_created_alter_contacts_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='list',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='заголовок'),
        ),
    ]
