# Generated by Django 4.0.4 on 2022-04-24 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_day_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='list',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Список'),
        ),
    ]
