from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("news", views.news, name="news"),
    path("preaching", views.preaching, name="preaching"),
    path("list_days", views.list_days, name="list_days"),
    path("contact", views.contact, name="contact"),
    path("history", views.history, name="history"),
    path("admin_menu", views.admin_menu, name="admin-menu"),
    path("admin_news", views.admin_news, name="admin-news"),
    path("admin_preaching", views.admin_preaching, name="admin-preaching"),
    path("admin_history", views.admin_history, name="admin-history"),
    path("add_days", views.add_days, name="add-days"),
    path("add_d", views.add_d, name="add-d"),
    path("add_news", views.add_news, name="add-news"),
    path("add_n", views.add_n, name="add-n"),
    path("add_preaching", views.add_preaching, name="add-preaching"),
    path("add_p", views.add_p, name="add-p"),
    path("add_history", views.add_history, name="add-history"),
    path("add_his", views.add_his, name="add-his"),
    path("add_contacts", views.add_contacts, name="add-contacts"),
    path("show_search", views.show_search, name="show-search"),
    path("show_days/<days_id>", views.show_days, name="show-days"),
    path("show_history/<history_id>", views.show_history, name="show-history"),
    path("show_news/<news_id>", views.show_news, name="show-news"),
    path("update_news/<news_id>", views.update_news, name="update-news"),
    path("update_n/<news_id>", views.update_n, name="update-n"),
    path("update_history/<history_id>", views.update_history, name="update-history"),
    path("update_h/<history_id>", views.update_h, name="update-h"),
    path("update_days/<days_id>", views.update_days, name="update-days"),
    path("update_contact/<contact_id>", views.update_contact, name="update-contact"),
    path("update_d/<days_id>", views.update_d, name="update-d"),
    path(
        "update_preaching/<preaching_id>",
        views.update_preaching,
        name="update-preaching",
    ),
    path("update_p/<preaching_id>", views.update_p, name="update-p"),
    path("delete_contact/<contact_id>", views.delete_contact, name="delete-contact"),
    path("delete_news/<news_id>", views.delete_news, name="delete-news"),
    path("delete_n/<news_id>", views.delete_n, name="delete-n"),
    path("delete_history/<history_id>", views.delete_history, name="delete-history"),
    path("delete_his/<history_id>", views.delete_his, name="delete-his"),
    path("delete_days/<days_id>", views.delete_days, name="delete-days"),
    path("delete_d/<days_id>", views.delete_d, name="delete-d"),
    path(
        "delete_preaching/<preaching_id>",
        views.delete_preaching,
        name="delete-preaching",
    ),
    path("delete_p/<preaching_id>", views.delete_p, name="delete-p"),
    path("show_preaching/<preaching_id>", views.show_preaching, name="show-preaching"),
    path(
        "show_index_preaching/<preaching_id>",
        views.show_index_preaching,
        name="show-index-preaching",
    ),
    path(
        "show_index_history/<history_id>",
        views.show_index_history,
        name="show-index-history",
    ),
    path("show_index_news/<news_id>", views.show_index_news, name="show-index-news"),
    path(
        "show_search_preaching/<preaching_id>",
        views.show_search_preaching,
        name="show-search-preaching",
    ),
    path(
        "show_search_history/<history_id>",
        views.show_search_history,
        name="show-search-history",
    ),
    path(
        "show_search_news/<news_id>",
        views.show_search_news,
        name="show-search-news",
    ),
    path(
        "show_admin_news/<news_id>",
        views.show_admin_news,
        name="show-admin-news",
    ),
    path(
        "show_admin_preaching/<preaching_id>",
        views.show_admin_preaching,
        name="show-admin-preaching",
    ),
    path(
        "show_admin_histor/<histor_id>",
        views.show_admin_histor,
        name="show-admin-histor",
    ),
]
